Delete from Produkt

INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0001','Toast','Aldi','al00100','Brot & Br�tchen');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0002','Mehrkornbr�tchen zum Aufbacken','Aldi','al00200','Brot & Br�tchen');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0003','Weizenbr�tchen zum Aufbacken','Aldi','al00300','Brot & Br�tchen');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0004','Schokobr�tchen','Aldi','00400','Fr�hst�ck');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0005','Nussecke','Aldi','00500','Fr�hst�ck');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0006','Hamburgerbr�tchen','Aldi','al00600','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0007','Kaffee','Aldi','al00700','Fr�hst�ck');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0008','Kissen','Aldi','al00800','Fr�hst�ck');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0009','M�sli','Aldi','al00900','Fr�hst�ck');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie,produktPreis) values ('0010','Kl. Wasser','Aldi','al01000','Getr�nke','1.74');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0011','Cola light','Aldi','al01100','Getr�nke');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0012','Bioriegel','Aldi','al01200','Schule');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0013','Knoppers','Aldi','al01300','Schule');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0014','Studentenfutter klein','Aldi','al01400','Schule');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0015','Apfel','Aldi','al01500','Obst');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0016','Kiwi','Aldi','al01600','Obst');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0017','Kartoffeln','Aldi','al01700','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0018','Katzenbeutel','Aldi','al01800','Haushalt & Katzen');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0019','Kl. M�llt�ten','Aldi','al01900','Haushalt & Katzen');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0020','Gr�ne M�llt�ten','Aldi','al02000','Haushalt & Katzen');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0021','Nivea','Aldi','al02100','K�rperpflege');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0022','Zahnpasta','Aldi','al002200','K�rperpflege');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0023','Duschgel','Aldi','al02300','K�rperpflege');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0024','K�chenrolle','Aldi','al02400','Haushalt & Katzen');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0025','Klopapier','Aldi','al02500','Haushalt & Katzen');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0026','Katzenfutter','Aldi','al02600','Hygiene & Katzen');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0027','Brekkies','Aldi','al02700','Hygiene & Katzen');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0028','Aufbackstangen / Aufbackbretzeln','Aldi','al02800','Schule');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0029','Eis','Aldi','al02900','S��es');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0030','Chicken Nuggets','Aldi','al03000','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0031','Karotten','Aldi','al03100','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0032','Salatgurke','Aldi','al03200','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0033','Zucchini','Aldi','al03300','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0034','Tomaten','Aldi','al03400','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0035','Salat','Aldi','al03500','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0036','Veg. Nuggets','Aldi','al03600','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0037','Veg. Burger','Aldi','al03700','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0038','Veg. Hackb�lchen','Aldi','al03800','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0039','K�setortellini','Aldi','al03900','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0040','Kl. Bratw�rstchen','Aldi','al04000','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0041','Basmatireis','Aldi','al04100','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0042','Nudeln mit K�seso�e','Aldi','al04200','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0043','Penne','Aldi','al04300','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0044','Bordolaise','Aldi','al04400','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0045','Scheibenk�se','Aldi','al04500','K�se & Milch');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0046','Zook�se','Aldi','al04600','K�se & Milch');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0047','Camenbert','Aldi','al04700','K�se & Milch');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0048','Tomatenmark','Aldi','al04800','K�se & Milch');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0049','Joghurt','Aldi','al04900','K�se & Milch');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0050','Fruchtquark','Aldi','al05000','K�se & Milch');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0051','Kroketten','Aldi','al05100','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0052','R�stiecken','Aldi','al05200','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0053','Loops','Aldi','al05300','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0054','Pommes','Aldi','al05400','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0055','R�sti','Aldi','al05500','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0056','Brokkoli','Aldi','al05600','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0057','Tomaten Ketchup','Aldi','al05700','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0058','Senf','Aldi','al05800','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0059','Butter','Aldi','al05900','K�se & Milch');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0060','Eier','Aldi','al06000','K�se & Milch');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0061','Milch','Aldi','al06100','K�se & Milch');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0062','�l normal','Aldi','al06200','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0063','Magarine','Aldi','al06300','K�se & Milch');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0064','Passierte Tomaten','Aldi','al06400','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0065','Erbsen klein','Aldi','al06500','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0066','Dosen-Tomaten','Aldi','al06600','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0067','Johannesbeeren','REWE','re00100','Fr�hst�ck');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0068','Currywurst','REWE','re00150','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0069','Baegels','REWE','re00170','Schule');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0070','Graubrot','REWE','re00200','Brot & Br�tchen');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0071','Vollkornbrot','REWE','re00201','Brot & Br�tchen');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0072','Clementine 7%','REWE','re00220','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0073','Miracoliso�e','REWE','re00300','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0074','Buchstabensuppe','REWE','re00350','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0075','Linsen','REWE','re00400','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0076','Brillent�cher','REWE','re00500','Haushalt & Katzen');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0077','Rahm-Blumenkohl','REWE','re00600','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0078','Dolomiti','REWE','re00600','S��es');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0079','Kaisergem�se','Aldi','al05610','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0080','Br�hw�rfe','Aldi','al03410','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0081','Veg. Bratwurst','Aldi','al03810','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0082','Corny','Aldi','al01210','Schule');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0083','Lebkuchen','Aldi','al00110','S��es');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0084','Gew�rzgurken','Aldi','al06310','Abendbrot');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0085','Kinderschokolade','Aldi','al01305','S��es');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0086','Tafel Schokolade','Aldi','al01310','S��es');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0087','Kesselchips','Aldi','al01410','S��es');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0088','Brechbohnen','Aldi','al06610','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0089','Ingwer','Aldi','al03110','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0090','Salatfix','Aldi','al03500','Mittag');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0091','Vollwaschmittel','Aldi','al02010','Haushalt & Katzen');
INSERT into Produkt (produktID,produktName,produktMarkt,produktRangfolge,produktKategorie) values ('0092','Colorwaschmittel','Aldi','al02020','Haushalt & Katzen');